/////user_profile màn hình trang cá nhân sửa trên thanh header

// Screens
export default ScreenName = {
  launch: 'LaunchComponent',
  login: 'LoginComponent',
  register: 'RegisterComponent',
  loading_hud: 'LoadingHUDComponent',
  home: 'HomeComponent',
  tour: 'TourComponent',
  inbox: 'InboxComponent',
  profile: 'ProfileComponent',
  more: 'MoreComponent',
  user_profie: 'UserProfileComponent',
  notification: 'NotificationComponent',
  post_create: 'PostCreateComponent',
  post_list: 'PostListComponent',
  post_detail: 'PostDetailComponent',
  search: 'SearchComponent',
  select_provider: 'SelectProviderComponent',
  view_photo: 'ViewPhotoComponent',
  post_more_option: 'PostMoreOptionActionSheet',
  select_language: 'SelectLanguageComponent',
  chat: 'ChatComponent',
  profile_update: 'SettingProfileComponent',
  tutorial: 'TutorialComponent',
  select_options: 'SelectOptionsComponent',
  checkIn: 'CheckInComponent',
  select_tour_time: 'SelectTourTimeComponent',
  CalandarDayFreeComponent: 'CalandarDayFreeComponent',
  post_share_action_sheet: 'PostShareActionSheet',
  modal_comment: 'ModalComment',
  modal_postcheckin: 'ModalCommentPostCheckIn',
  modal_cancel_post: 'ModalCancelPost',
  launchProfile: 'LaunchProfileComponent',
  cameraroll: 'CameraRollComponent',
  register_agent: 'RegisterAgentComponent',
  register_guide: 'RegisterGuideComponent',
  register_select_card: 'RegisterSelectCardActionSheet',
  share_post: 'SharePostComponent',
  share_post_as_link: 'SharePostAsLinkComponent',
  camera: 'CameraComponent',
  profile_infomation: 'ProfileInformationComponent',
  date_picker: 'DatePickerActionSheet',
  date: 'DateActionSheet',
  apply_tour: 'ApplyTourComponent',
  user_apply: 'UserApplyListComponent',
  like_list_post: 'PostLikeListComponent',
  apply_list_post: 'PostApplyListComponent',
  user_friend_list: 'UserFriendListComponent',
  post_saved: 'PostSavedComponent',
  reset_password: 'ResetPasswordComponent',
  change_password: 'ChangePasswordComponent',
  tour_review_component: 'TourReviewComponent',
  location_list_component: 'LocationListComponent',
  AddEventComponent: 'AddEventComponent',
  FreeDayListComponent: 'FreeDayListComponent',
  ActionSheet: 'ActionSheet',
  // WebViewComponent: 'WebViewComponent',
  FriendList: 'FriendList',
  RatingInfo: 'RatingInfo',
  InvitedUserOther: 'InvitedUserOther',
  ModalEditComment: 'InputMessageView',
  PostCheckInComponent: 'CheckInPostComponent',
  ShowImageCheckInComponent: 'ShowImageCheckInComponent',
  // RatingInfo: 'RatingInfo',
  // InvitedUserOther: 'InvitedUserOther',
  // ModalEditComment: 'InputMessageView',
  PostTrip: 'PostTrip',
  MoreInfo: 'MoreInfo',
  PublicProfile: 'PublicProfileComponent',
  Guide_Home: 'GuideComponent',
  Agent_Home: 'AgentComponent',
  Group: 'GroupComponent',
  HomeGroup: 'HomeGroupComponent',
  InformationGroup: 'InformationGroupComponent',
  SearchAllUser: 'SearchAllUser',
  SearchAllPost: 'SeaarchAllPost',
  SearchAllTour: 'SeaarchAllTour',
  AccountVerificationComponent: 'AccountVerificationComponent',
  tour_guide_like: 'ProfileLikeComponent',
  GalleryComponent: 'GalleryComponent',
  GalleryGroupComponent: 'GalleryGroupComponent',
  CreateAlbum: 'CreateAlbum',
  DetailPhotos: 'DetailPhotosComponent',
  ActiveAccount: 'ActiveAccountComponent',
  modal_comment_group_container: 'ModalCommentGroupContainer',
  AskedToJoinTheGroup: 'AskedToJoinTheGroupComponent',
  GroupMembersApproval: 'GroupMembersApproval',
  GroupPostApproval: 'GroupPostApproval',
  DetailGuideAgent: 'PostDetailGuideAgent',
  InviteMemberMe: 'InviteMemberContainer',
  ImageGalleryComponent: 'ImageGalleryComponent',
  MoreOptionGallery: 'ModalMoreOptionGallery',
  PostDetailGroupComponent: 'PostDetailGroupComponent',
  modal_cancel_back_group_post: 'ModalCancelBackGroupPost',

  ListTourAgentApplyGuider: 'ListTourAgentApplyGuide',
  request_add_friend_list: 'RequestAddFriendListContainer',

  PostDetailHomeGroup: 'PostDetailHomeGroup',


  //register screen term and policy
  TermPolicy: 'TermPolicyComponent',
  pushShareGroup: 'pushShareGroupComponent',
  AddGuiderComponent: 'AddGuiderComponent',


  //
  SelectLanguageInviteGuider: 'SelectLanguageInviteGuider',
  // phong lời mời đi tuor
  Invitationtojointour: 'Invitationtojointour',
  ListGuideApply: 'ListGuideApply',

  ShowModalUserProfile: 'copyUserProfilecomponent',
  ListGuideApplyTour: 'ListGuideApplyTour',
  ListGuideTour: 'ListGuideTour',
  ListGuideInvited: 'ListGuideInvited',
  DetailTourInvited: 'DetailTourInvited',
  ShowTrackingHistoryGuide: 'TrackingHistoryGuideContainer',

  ShowTrackingHistoryAgent: 'TrackingHistoryAgentContainer',
  PostDetailTipComponent: 'PostDetailTipComponent',
  ListGuideUpcoming: 'ListGuideUpcoming',
  ReportComponent: 'ReportComponent',
  SeeAllPostTip: 'SeeAllPostTip',
  ListReportComponent: 'ListReportComponent',
  ReviewComponent: 'ReviewComponent',
  ShowHotPostRelateds: 'HotPostRelatedContainer',
  GuideFinishComponent: 'GuideFinishComponent',
  modal_Report: 'ModalCommentReport',


}
